# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 2018_05_14_075632) do

  create_table "guards", force: :cascade do |t|
    t.string "extra"
    t.string "user_id"
    t.string "dabi"
    t.string "roano"
    t.string "lroi"
    t.string "gaius"
    t.string "kamaella"
    t.string "jiwon"
    t.string "roze"
    t.string "elleonol"
    t.string "tartan"
    t.string "pransis"
    t.string "mico"
    t.string "ariel"
    t.string "kaizer"
    t.string "rin"
    t.string "miller"
    t.string "garen"
    t.string "anna"
    t.string "chino"
    t.string "silvia"
    t.string "ceok"
    t.string "eren"
    t.string "wi"
    t.string "bibian"
    t.string "seahorseleader"
    t.string "india"
    t.string "mina"
    t.string "rilliana"
    t.string "hwarang"
    t.string "parao"
    t.string "fllea"
    t.string "keyboardwarriora"
    t.string "deepredmoon"
    t.string "kralisa"
    t.string "rabiel"
    t.string "andreas"
    t.string "graphite"
    t.string "fausutu"
    t.string "misha"
    t.string "rael"
    t.string "darel"
    t.string "kaiyhan"
    t.string "ran"
    t.string "boni"
    t.string "sera"
    t.string "mika"
    t.string "roksannue"
    t.string "kloud"
    t.string "verna"
    t.string "angel"
    t.string "violle"
    t.string "erica"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "monsters", force: :cascade do |t|
    t.string "extra"
    t.string "user_id"
    t.string "dabi"
    t.string "roano"
    t.string "lroi"
    t.string "gaius"
    t.string "kamaella"
    t.string "jiwon"
    t.string "roze"
    t.string "elleonol"
    t.string "tartan"
    t.string "pransis"
    t.string "mico"
    t.string "ariel"
    t.string "kaizer"
    t.string "rin"
    t.string "miller"
    t.string "garen"
    t.string "anna"
    t.string "chino"
    t.string "silvia"
    t.string "ceok"
    t.string "eren"
    t.string "wi"
    t.string "bibian"
    t.string "seahorseleader"
    t.string "india"
    t.string "mina"
    t.string "rilliana"
    t.string "hwarang"
    t.string "parao"
    t.string "fllea"
    t.string "keyboardwarriora"
    t.string "deepredmoon"
    t.string "kralisa"
    t.string "rabiel"
    t.string "andreas"
    t.string "graphite"
    t.string "fausutu"
    t.string "misha"
    t.string "rael"
    t.string "darel"
    t.string "kaiyhan"
    t.string "ran"
    t.string "boni"
    t.string "sera"
    t.string "mika"
    t.string "roksannue"
    t.string "kloud"
    t.string "verna"
    t.string "angel"
    t.string "violle"
    t.string "erica"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "necklaces", force: :cascade do |t|
    t.string "extra"
    t.string "user_id"
    t.string "dabi"
    t.string "roano"
    t.string "lroi"
    t.string "gaius"
    t.string "kamaella"
    t.string "jiwon"
    t.string "roze"
    t.string "elleonol"
    t.string "tartan"
    t.string "pransis"
    t.string "mico"
    t.string "ariel"
    t.string "kaizer"
    t.string "rin"
    t.string "miller"
    t.string "garen"
    t.string "anna"
    t.string "chino"
    t.string "silvia"
    t.string "ceok"
    t.string "eren"
    t.string "wi"
    t.string "bibian"
    t.string "seahorseleader"
    t.string "india"
    t.string "mina"
    t.string "rilliana"
    t.string "hwarang"
    t.string "parao"
    t.string "fllea"
    t.string "keyboardwarriora"
    t.string "deepredmoon"
    t.string "kralisa"
    t.string "rabiel"
    t.string "andreas"
    t.string "graphite"
    t.string "fausutu"
    t.string "misha"
    t.string "rael"
    t.string "darel"
    t.string "kaiyhan"
    t.string "ran"
    t.string "boni"
    t.string "sera"
    t.string "mika"
    t.string "roksannue"
    t.string "kloud"
    t.string "verna"
    t.string "angel"
    t.string "violle"
    t.string "erica"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "rings", force: :cascade do |t|
    t.string "extra"
    t.string "user_id"
    t.string "dabi"
    t.string "roano"
    t.string "lroi"
    t.string "gaius"
    t.string "kamaella"
    t.string "jiwon"
    t.string "roze"
    t.string "elleonol"
    t.string "tartan"
    t.string "pransis"
    t.string "mico"
    t.string "ariel"
    t.string "kaizer"
    t.string "rin"
    t.string "miller"
    t.string "garen"
    t.string "anna"
    t.string "chino"
    t.string "silvia"
    t.string "ceok"
    t.string "eren"
    t.string "wi"
    t.string "bibian"
    t.string "seahorseleader"
    t.string "india"
    t.string "mina"
    t.string "rilliana"
    t.string "hwarang"
    t.string "parao"
    t.string "fllea"
    t.string "keyboardwarriora"
    t.string "deepredmoon"
    t.string "kralisa"
    t.string "rabiel"
    t.string "andreas"
    t.string "graphite"
    t.string "fausutu"
    t.string "misha"
    t.string "rael"
    t.string "darel"
    t.string "kaiyhan"
    t.string "ran"
    t.string "boni"
    t.string "sera"
    t.string "mika"
    t.string "roksannue"
    t.string "kloud"
    t.string "verna"
    t.string "angel"
    t.string "violle"
    t.string "erica"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "staminabeads", force: :cascade do |t|
    t.string "extra"
    t.string "user_id"
    t.string "dabi"
    t.string "roano"
    t.string "lroi"
    t.string "gaius"
    t.string "kamaella"
    t.string "jiwon"
    t.string "roze"
    t.string "elleonol"
    t.string "tartan"
    t.string "pransis"
    t.string "mico"
    t.string "ariel"
    t.string "kaizer"
    t.string "rin"
    t.string "miller"
    t.string "garen"
    t.string "anna"
    t.string "chino"
    t.string "silvia"
    t.string "ceok"
    t.string "eren"
    t.string "wi"
    t.string "bibian"
    t.string "seahorseleader"
    t.string "india"
    t.string "mina"
    t.string "rilliana"
    t.string "hwarang"
    t.string "parao"
    t.string "fllea"
    t.string "keyboardwarriora"
    t.string "deepredmoon"
    t.string "kralisa"
    t.string "rabiel"
    t.string "andreas"
    t.string "graphite"
    t.string "fausutu"
    t.string "misha"
    t.string "rael"
    t.string "darel"
    t.string "kaiyhan"
    t.string "ran"
    t.string "boni"
    t.string "sera"
    t.string "mika"
    t.string "roksannue"
    t.string "kloud"
    t.string "verna"
    t.string "angel"
    t.string "violle"
    t.string "erica"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "users", force: :cascade do |t|
    t.string "email", default: "", null: false
    t.string "encrypted_password", default: "", null: false
    t.string "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer "sign_in_count", default: 0, null: false
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.string "current_sign_in_ip"
    t.string "last_sign_in_ip"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["email"], name: "index_users_on_email", unique: true
    t.index ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true
  end

  create_table "weapons", force: :cascade do |t|
    t.string "extra"
    t.string "user_id"
    t.string "dabi"
    t.string "roano"
    t.string "lroi"
    t.string "gaius"
    t.string "kamaella"
    t.string "jiwon"
    t.string "roze"
    t.string "elleonol"
    t.string "tartan"
    t.string "pransis"
    t.string "mico"
    t.string "ariel"
    t.string "kaizer"
    t.string "rin"
    t.string "miller"
    t.string "garen"
    t.string "anna"
    t.string "chino"
    t.string "silvia"
    t.string "ceok"
    t.string "eren"
    t.string "wi"
    t.string "bibian"
    t.string "seahorseleader"
    t.string "india"
    t.string "mina"
    t.string "rilliana"
    t.string "hwarang"
    t.string "parao"
    t.string "fllea"
    t.string "keyboardwarriora"
    t.string "deepredmoon"
    t.string "kralisa"
    t.string "rabiel"
    t.string "andreas"
    t.string "graphite"
    t.string "fausutu"
    t.string "misha"
    t.string "rael"
    t.string "darel"
    t.string "kaiyhan"
    t.string "ran"
    t.string "boni"
    t.string "sera"
    t.string "mika"
    t.string "roksannue"
    t.string "kloud"
    t.string "verna"
    t.string "angel"
    t.string "violle"
    t.string "erica"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

end
